package com.example.tftitemapplication

object TftItemsUtil {
    private val imageMapToDrawable = mapOf(
        "tft14_zericyberneticitem_radiant" to R.drawable.tft14_zericyberneticitem_radiant,
        "tft14_naafiricyberneticitem_radiant" to R.drawable.tft14_naafiricyberneticitem_radiant,
        "tft14_varuscyberneticitem_radiant" to R.drawable.tft14_varuscyberneticitem_radiant,
        "tft14_sejuanicyberneticitem_radiant" to R.drawable.tft14_sejuanicyberneticitem_radiant,
        "tft14_jaxcyberneticitem_radiant" to R.drawable.tft14_jaxcyberneticitem_radiant,
        "tft14_mordekaisercyberneticitem_radiant" to R.drawable.tft14_mordekaisercyberneticitem_radiant,
        "tft14_jhincyberneticitem_radiant" to R.drawable.tft14_jhincyberneticitem_radiant,
        "tft_item_emptybag" to R.drawable.tft_item_emptybag,
        "tft_item_artifact_spectralcutlass" to R.drawable.tft_item_artifact_spectralcutlass,
        "tft5_item_guardianangelradiant" to R.drawable.tft5_item_guardianangelradiant,
        "tft5_item_gargoylestoneplateradiant" to R.drawable.tft5_item_gargoylestoneplateradiant,
        "tft_item_steraksgage" to R.drawable.tft_item_steraksgage,
        "tft_item_artifact_blightingjewel" to R.drawable.tft_item_artifact_blightingjewel,
        "tft5_item_runaanshurricaneradiant" to R.drawable.tft5_item_runaanshurricaneradiant,
        "tft5_item_bloodthirsterradiant" to R.drawable.tft5_item_bloodthirsterradiant,
        "tft_item_unstabletreasurechest" to R.drawable.tft_item_unstabletreasurechest,
        "tft5_item_ionicsparkradiant" to R.drawable.tft5_item_ionicsparkradiant,
        "tft5_item_spectralgauntletradiant" to R.drawable.tft5_item_spectralgauntletradiant,
        "tft_item_quicksilver" to R.drawable.tft_item_quicksilver,
        "tft_item_unstableconcoction" to R.drawable.tft_item_unstableconcoction,
        "tft5_item_handofjusticeradiant" to R.drawable.tft5_item_handofjusticeradiant,
        "tft_item_artifact_silvermeredawn" to R.drawable.tft_item_artifact_silvermeredawn,
        "tft_item_thiefsgloves" to R.drawable.tft_item_thiefsgloves,
        "tft_item_guardianangel" to R.drawable.tft_item_guardianangel,
        "tft5_item_statikkshivradiant" to R.drawable.tft5_item_statikkshivradiant,
        "tft_item_deathblade" to R.drawable.tft_item_deathblade,
        "tft5_item_morellonomiconradiant" to R.drawable.tft5_item_morellonomiconradiant,
        "tft_item_titansresolve" to R.drawable.tft_item_titansresolve,
        "tft5_item_redemptionradiant" to R.drawable.tft5_item_redemptionradiant,
        "tft_item_bloodthirster" to R.drawable.tft_item_bloodthirster,
        "tft5_item_crownguardradiant" to R.drawable.tft5_item_crownguardradiant,
        "tft5_item_spearofshojinradiant" to R.drawable.tft5_item_spearofshojinradiant,
        "tft14_item_armorclademblemitem" to R.drawable.tft14_item_armorclademblemitem,
        "tft5_item_sunfirecaperadiant" to R.drawable.tft5_item_sunfirecaperadiant,
        "tft5_item_quicksilverradiant" to R.drawable.tft5_item_quicksilverradiant,
        "tft_item_artifact_unendingdespair" to R.drawable.tft_item_artifact_unendingdespair,
        "tft_item_rabadonsdeathcap" to R.drawable.tft_item_rabadonsdeathcap,
        "tft_item_shroud" to R.drawable.tft_item_shroud,
        "tft14_item_divinicorpemblemitem" to R.drawable.tft14_item_divinicorpemblemitem,
        "tft_item_archangelsstaff" to R.drawable.tft_item_archangelsstaff,
        "tft_item_artifact_suspicioustrenchcoat" to R.drawable.tft_item_artifact_suspicioustrenchcoat,
        "tft4_item_ornnanimavisage" to R.drawable.tft4_item_ornnanimavisage,
        "tft_item_nightharvester" to R.drawable.tft_item_nightharvester,
        "tft_item_leviathan" to R.drawable.tft_item_leviathan,
        "tft5_item_hextechgunbladeradiant" to R.drawable.tft5_item_hextechgunbladeradiant,
        "tft_item_runaanshurricane" to R.drawable.tft_item_runaanshurricane,
        "tft_item_adaptivehelm" to R.drawable.tft_item_adaptivehelm,
        "tft_item_tacticiansscepter" to R.drawable.tft_item_tacticiansscepter,
        "tft14_item_darkwebemblemitem" to R.drawable.tft14_item_darkwebemblemitem,
        "tft14_item_controlleremblemitem" to R.drawable.tft14_item_controlleremblemitem,
        "tft5_item_giantslayerradiant" to R.drawable.tft5_item_giantslayerradiant,
        "tft9_item_ornntrickstersglass" to R.drawable.tft9_item_ornntrickstersglass,
        "tft_item_crownguard" to R.drawable.tft_item_crownguard,
        "tft14_item_guardianemblemitem" to R.drawable.tft14_item_guardianemblemitem,
        "tft_item_redemption" to R.drawable.tft_item_redemption,
        "tft_item_morellonomicon" to R.drawable.tft_item_morellonomicon,
        "tft14_item_marksmanemblemitem" to R.drawable.tft14_item_marksmanemblemitem,
        "tft5_item_nightharvesterradiant" to R.drawable.tft5_item_nightharvesterradiant,
        "tft_item_locketoftheironsolari" to R.drawable.tft_item_locketoftheironsolari,
        "tft_item_madredsbloodrazor" to R.drawable.tft_item_madredsbloodrazor,
        "tft14_item_mobemblemitem" to R.drawable.tft14_item_mobemblemitem,
        "tft_item_tacticiansring" to R.drawable.tft_item_tacticiansring,
        "tft_item_frozenheart" to R.drawable.tft_item_frozenheart,
        "tft_item_eternalflame" to R.drawable.tft_item_eternalflame,
        "tft14_item_swiftemblemitem" to R.drawable.tft14_item_swiftemblemitem,
        "tft_item_artifact_fishbones" to R.drawable.tft_item_artifact_fishbones,
        "tft14_item_ballistekemblemitem" to R.drawable.tft14_item_ballistekemblemitem,
        "tft_item_lastwhisper" to R.drawable.tft_item_lastwhisper,
        "tft_item_statikkshiv" to R.drawable.tft_item_statikkshiv,
        "tft_item_bramblevest" to R.drawable.tft_item_bramblevest,
        "tft_item_spectralgauntlet" to R.drawable.tft_item_spectralgauntlet,
        "tft_item_ionicspark" to R.drawable.tft_item_ionicspark,
        "tft5_item_thiefsglovesradiant" to R.drawable.tft5_item_thiefsglovesradiant,
        "tft14_item_thirstyemblemitem" to R.drawable.tft14_item_thirstyemblemitem,
        "tft_item_rapidfirecannon" to R.drawable.tft_item_rapidfirecannon,
        "tft14_item_techieemblemitem" to R.drawable.tft14_item_techieemblemitem,
        "tft14_item_cutteremblemitem" to R.drawable.tft14_item_cutteremblemitem,
        "tft_item_warmogsarmor" to R.drawable.tft_item_warmogsarmor,
        "tft4_item_ornndeathsdefiance" to R.drawable.tft4_item_ornndeathsdefiance,
        "tft_item_moonstone" to R.drawable.tft_item_moonstone,
        "tft_item_spatula" to R.drawable.tft_item_spatula,
        "tft5_item_warmogsarmorradiant" to R.drawable.tft5_item_warmogsarmorradiant,
        "tft14_item_edgerunneremblemitem" to R.drawable.tft14_item_edgerunneremblemitem,
        "tft14_item_bruiseremblemitem" to R.drawable.tft14_item_bruiseremblemitem,
        "tft5_item_rabadonsdeathcapradiant" to R.drawable.tft5_item_rabadonsdeathcapradiant,
        "tft_item_forceofnature" to R.drawable.tft_item_forceofnature,
        "tft5_item_bramblevestradiant" to R.drawable.tft5_item_bramblevestradiant,
        "tft5_item_adaptivehelmradiant" to R.drawable.tft5_item_adaptivehelmradiant,
        "tft_item_hextechgunblade" to R.drawable.tft_item_hextechgunblade,
        "tft_item_jeweledgauntlet" to R.drawable.tft_item_jeweledgauntlet,
        "tft_item_powergauntlet" to R.drawable.tft_item_powergauntlet,
        "tft5_item_bluebuffradiant" to R.drawable.tft5_item_bluebuffradiant,
        "tft14_item_streetdemonemblemitem" to R.drawable.tft14_item_streetdemonemblemitem,
        "tft_item_artifact_seekersarmguard" to R.drawable.tft_item_artifact_seekersarmguard,
        "tft9_item_ornnhorizonfocus" to R.drawable.tft9_item_ornnhorizonfocus,
        "tft14_item_immortalemblemitem" to R.drawable.tft14_item_immortalemblemitem,
        "tft_item_infinityedge" to R.drawable.tft_item_infinityedge,
        "tft_item_bluebuff" to R.drawable.tft_item_bluebuff,
        "tft_item_dragonsclaw" to R.drawable.tft_item_dragonsclaw,
        "tft4_item_ornnmuramana" to R.drawable.tft4_item_ornnmuramana,
        "tft_item_gargoylestoneplate" to R.drawable.tft_item_gargoylestoneplate,
        "tft4_item_ornninfinityforce" to R.drawable.tft4_item_ornninfinityforce,
        "tft_item_artifact_ludenstempest" to R.drawable.tft_item_artifact_ludenstempest,
        "tft_item_radiantvirtue" to R.drawable.tft_item_radiantvirtue,
        "tft_item_redbuff" to R.drawable.tft_item_redbuff,
        "tft_item_artifact_lichbane" to R.drawable.tft_item_artifact_lichbane,
        "tft4_item_ornnthecollector" to R.drawable.tft4_item_ornnthecollector,
        "tft5_item_deathbladeradiant" to R.drawable.tft5_item_deathbladeradiant,
        "tft4_item_ornnzhonyasparadox" to R.drawable.tft4_item_ornnzhonyasparadox,
        "tft_item_zekesherald" to R.drawable.tft_item_zekesherald,
        "tft_item_spearofshojin" to R.drawable.tft_item_spearofshojin,
        "tft5_item_dragonsclawradiant" to R.drawable.tft5_item_dragonsclawradiant,
        "tft5_item_titansresolveradiant" to R.drawable.tft5_item_titansresolveradiant,
        "tft_item_artifact_mittens" to R.drawable.tft_item_artifact_mittens,
        "tft14_jhincyberneticitem" to R.drawable.tft14_jhincyberneticitem,
        "tft9_item_ornndeathfiregrasp" to R.drawable.tft9_item_ornndeathfiregrasp,
        "tft5_item_zzrotportalradiant" to R.drawable.tft5_item_zzrotportalradiant,
        "tft4_item_ornnranduinssanctum" to R.drawable.tft4_item_ornnranduinssanctum,
        "tft7_item_shimmerscaleheartofgold" to R.drawable.tft7_item_shimmerscaleheartofgold,
        "tft14_naafiricyberneticitem" to R.drawable.tft14_naafiricyberneticitem,
        "tft_item_guinsoosrageblade" to R.drawable.tft_item_guinsoosrageblade,
        "tft_item_chainvest" to R.drawable.tft_item_chainvest,
        "tft5_item_guinsoosragebladeradiant" to R.drawable.tft5_item_guinsoosragebladeradiant,
        "tft14_mordekaisercyberneticitem" to R.drawable.tft14_mordekaisercyberneticitem,
        "tft5_item_archangelsstaffradiant" to R.drawable.tft5_item_archangelsstaffradiant,
        "tft_item_artifact_lightshieldcrest" to R.drawable.tft_item_artifact_lightshieldcrest,
        "tft14_zericyberneticitem" to R.drawable.tft14_zericyberneticitem,
        "tft_item_artifact_horizonfocus" to R.drawable.tft_item_artifact_horizonfocus,
        "tft_item_giantsbelt" to R.drawable.tft_item_giantsbelt,
        "tft5_item_jeweledgauntletradiant" to R.drawable.tft5_item_jeweledgauntletradiant,
        "tft5_item_lastwhisperradiant" to R.drawable.tft5_item_lastwhisperradiant,
        "tft14_item_strongemblemitem" to R.drawable.tft14_item_strongemblemitem,
        "tft5_item_infinityedgeradiant" to R.drawable.tft5_item_infinityedgeradiant,
        "tft4_item_ornnobsidiancleaver" to R.drawable.tft4_item_ornnobsidiancleaver,
        "tft14_varuscyberneticitem" to R.drawable.tft14_varuscyberneticitem,
        "tft14_sejuanicyberneticitem" to R.drawable.tft14_sejuanicyberneticitem,
        "tft_item_bansheesveil" to R.drawable.tft_item_bansheesveil,
        "tft5_item_rapidfirecannonradiant" to R.drawable.tft5_item_rapidfirecannonradiant,
        "tft_item_negatroncloak" to R.drawable.tft_item_negatroncloak,
        "tft_item_needlesslylargerod" to R.drawable.tft_item_needlesslylargerod,
        "tft_item_tearofthegoddess" to R.drawable.tft_item_tearofthegoddess,
        "tft5_item_steraksgageradiant" to R.drawable.tft5_item_steraksgageradiant,
        "tft14_jaxcyberneticitem" to R.drawable.tft14_jaxcyberneticitem,
        "tft_item_spite" to R.drawable.tft_item_spite,
        "tft9_item_ornnhullbreaker" to R.drawable.tft9_item_ornnhullbreaker,
        "tft14_item_nitro_chromecounter" to R.drawable.tft14_item_nitro_chromecounter,
        "tft_item_supportknightsvow" to R.drawable.tft_item_supportknightsvow,
        "tft5_item_trapclawradiant" to R.drawable.tft5_item_trapclawradiant,
        "tft_item_chalice" to R.drawable.tft_item_chalice,
        "tft7_item_shimmerscalegamblersblade" to R.drawable.tft7_item_shimmerscalegamblersblade,
        "tft_item_artifact_prowlersclaw" to R.drawable.tft_item_artifact_prowlersclaw,
        "tft_item_artifact_rapidfirecannon" to R.drawable.tft_item_artifact_rapidfirecannon,
        "tft_item_sparringgloves" to R.drawable.tft_item_sparringgloves,
        "tft_item_bfsword" to R.drawable.tft_item_bfsword,
        "tft_item_artifact_innervatinglocket" to R.drawable.tft_item_artifact_innervatinglocket,
        "tft_item_artifact_witsend" to R.drawable.tft_item_artifact_witsend,
        "tft_item_recurvebow" to R.drawable.tft_item_recurvebow,
        "tft5_item_leviathanradiant" to R.drawable.tft5_item_leviathanradiant,
        "tft7_item_shimmerscalemogulsmail" to R.drawable.tft7_item_shimmerscalemogulsmail,
        "tft_item_aegisofthelegion" to R.drawable.tft_item_aegisofthelegion,
        "tft5_item_frozenheartradiant" to R.drawable.tft5_item_frozenheartradiant,
        "tft_item_artifact_talismanofascension" to R.drawable.tft_item_artifact_talismanofascension,
        "tft_item_zephyr" to R.drawable.tft_item_zephyr,
        "tft_item_fryingpan" to R.drawable.tft_item_fryingpan
    )

    fun getDrawable(itemName: String): Int {
        return imageMapToDrawable[itemName.lowercase()] ?: R.drawable.tft_item_debugbase
    }

    private val tftItemMap = mapOf(
        // Cybernetic Items
        "TFT14_ZeriCyberneticItem_Radiant" to "Flux Capacitor (Radiant)",
        "TFT14_NaafiriCyberneticItem_Radiant" to "Hyper Fangs (Radiant)",
        "TFT14_VarusCyberneticItem_Radiant" to "Holobow (Radiant)",
        "TFT14_SejuaniCyberneticItem_Radiant" to "Cybercoil (Radiant)",
        "TFT14_JaxCyberneticItem_Radiant" to "Repulsor Lantern (Radiant)",
        "TFT14_MordekaiserCyberneticItem_Radiant" to "Corrupted Chassis (Radiant)",
        "TFT14_JhinCyberneticItem_Radiant" to "Pulse Stabilizer (Radiant)",
        "TFT14_JhinCyberneticItem" to "Pulse Stabilizer",
        "TFT14_NaafiriCyberneticItem" to "Hyper Fangs",
        "TFT14_MordekaiserCyberneticItem" to "Corrupted Chassis",
        "TFT14_ZeriCyberneticItem" to "Flux Capacitor",
        "TFT14_VarusCyberneticItem" to "Holobow",
        "TFT14_SejuaniCyberneticItem" to "Cybercoil",
        "TFT14_JaxCyberneticItem" to "Repulsor Lantern",

        // Basic Items
        "TFT_Item_EmptyBag" to "Empty Bag",
        "TFT_Item_SteraksGage" to "Sterak's Gage",
        "TFT_Item_Quicksilver" to "Quicksilver",
        "TFT_Item_UnstableConcoction" to "Hand of Justice",
        "TFT_Item_ThiefsGloves" to "Thief's Gloves",
        "TFT_Item_GuardianAngel" to "Edge of Night",
        "TFT_Item_Deathblade" to "Deathblade",
        "TFT_Item_TitansResolve" to "Titan's Resolve",
        "TFT_Item_Bloodthirster" to "Bloodthirster",
        "TFT_Item_RabadonsDeathcap" to "Rabadon's Deathcap",
        "TFT_Item_Shroud" to "Shroud",
        "TFT_Item_ArchangelsStaff" to "Archangel's Staff",
        "TFT_Item_NightHarvester" to "Steadfast Heart",
        "TFT_Item_Leviathan" to "Leviathan",
        "TFT_Item_RunaansHurricane" to "Runaan's Hurricane",
        "TFT_Item_AdaptiveHelm" to "Adaptive Helm",
        "TFT_Item_TacticiansScepter" to "Tactician's Scepter",
        "TFT_Item_Crownguard" to "Crownguard",
        "TFT_Item_Redemption" to "Redemption",
        "TFT_Item_Morellonomicon" to "Morellonomicon",
        "TFT_Item_LocketOfTheIronSolari" to "Locket of the Iron Solari",
        "TFT_Item_MadredsBloodrazor" to "Giant Slayer",
        "TFT_Item_TacticiansRing" to "Tactician's Ring",
        "TFT_Item_FrozenHeart" to "Frozen Heart",
        "TFT_Item_EternalFlame" to "Eternal Flame",
        "TFT_Item_LastWhisper" to "Last Whisper",
        "TFT_Item_StatikkShiv" to "Statikk Shiv",
        "TFT_Item_BrambleVest" to "Bramble Vest",
        "TFT_Item_SpectralGauntlet" to "Spectral Gauntlet",
        "TFT_Item_IonicSpark" to "Ionic Spark",
        "TFT_Item_RapidFireCannon" to "Rapid Firecannon",
        "TFT_Item_WarmogsArmor" to "Warmog's Armor",
        "TFT_Item_Moonstone" to "Moonstone",
        "TFT_Item_Spatula" to "Spatula",
        "TFT_Item_ForceOfNature" to "Force of Nature",
        "TFT_Item_HextechGunblade" to "Hextech Gunblade",
        "TFT_Item_JeweledGauntlet" to "Jeweled Gauntlet",
        "TFT_Item_PowerGauntlet" to "Power Gauntlet",
        "TFT_Item_InfinityEdge" to "Infinity Edge",
        "TFT_Item_BlueBuff" to "Blue Buff",
        "TFT_Item_DragonsClaw" to "Dragon's Claw",
        "TFT_Item_GargoyleStoneplate" to "Gargoyle Stoneplate",
        "TFT_Item_RadiantVirtue" to "Radiant Virtue",
        "TFT_Item_RedBuff" to "Red Buff",
        "TFT_Item_ZekesHerald" to "Zeke's Herald",
        "TFT_Item_SpearOfShojin" to "Spear of Shojin",
        "TFT_Item_GuinsoosRageblade" to "Guinsoo's Rageblade",
        "TFT_Item_ChainVest" to "Chain Vest",
        "TFT_Item_GiantsBelt" to "Giant's Belt",
        "TFT_Item_BansheesVeil" to "Banshee's Veil",
        "TFT_Item_NegatronCloak" to "Negatron Cloak",
        "TFT_Item_NeedlesslyLargeRod" to "Needlessly Large Rod",
        "TFT_Item_TearOfTheGoddess" to "Tear of the Goddess",
        "TFT_Item_Spite" to "Spite",
        "TFT_Item_SupportKnightsVow" to "Knight's Vow",
        "TFT_Item_Chalice" to "Chalice",
        "TFT_Item_SparringGloves" to "Sparring Gloves",
        "TFT_Item_BFSword" to "B.F. Sword",
        "TFT_Item_RecurveBow" to "Recurve Bow",
        "TFT_Item_AegisOfTheLegion" to "Aegis of the Legion",
        "TFT_Item_Zephyr" to "Zephyr",
        "TFT_Item_FryingPan" to "Frying Pan",
        "TFT_Item_UnstableTreasureChest" to "Unstable Treasure Chest",

        // Radiant Items (TFT5)
        "TFT5_Item_GuardianAngelRadiant" to "Edge of Night (Radiant)",
        "TFT5_Item_GargoyleStoneplateRadiant" to "Gargoyle Stoneplate (Radiant)",
        "TFT5_Item_RunaansHurricaneRadiant" to "Runaan's Hurricane (Radiant)",
        "TFT5_Item_BloodthirsterRadiant" to "Bloodthirster (Radiant)",
        "TFT5_Item_IonicSparkRadiant" to "Ionic Spark (Radiant)",
        "TFT5_Item_SpectralGauntletRadiant" to "Spectral Gauntlet (Radiant)",
        "TFT5_Item_HandOfJusticeRadiant" to "Hand of Justice (Radiant)",
        "TFT5_Item_StatikkShivRadiant" to "Statikk Shiv (Radiant)",
        "TFT5_Item_MorellonomiconRadiant" to "Morellonomicon (Radiant)",
        "TFT5_Item_RedemptionRadiant" to "Redemption (Radiant)",
        "TFT5_Item_CrownguardRadiant" to "Crownguard (Radiant)",
        "TFT5_Item_SpearOfShojinRadiant" to "Spear of Shojin (Radiant)",
        "TFT5_Item_SunfireCapeRadiant" to "Sunfire Cape (Radiant)",
        "TFT5_Item_QuicksilverRadiant" to "Quicksilver (Radiant)",
        "TFT5_Item_HextechGunbladeRadiant" to "Hextech Gunblade (Radiant)",
        "TFT5_Item_GiantSlayerRadiant" to "Giant Slayer (Radiant)",
        "TFT5_Item_NightHarvesterRadiant" to "Night Harvester (Radiant)",
        "TFT5_Item_ThiefsGlovesRadiant" to "Thief's Gloves (Radiant)",
        "TFT5_Item_WarmogsArmorRadiant" to "Warmog's Armor (Radiant)",
        "TFT5_Item_RabadonsDeathcapRadiant" to "Rabadon's Deathcap (Radiant)",
        "TFT5_Item_BrambleVestRadiant" to "Bramble Vest (Radiant)",
        "TFT5_Item_AdaptiveHelmRadiant" to "Adaptive Helm (Radiant)",
        "TFT5_Item_BlueBuffRadiant" to "Blue Buff (Radiant)",
        "TFT5_Item_DeathbladeRadiant" to "Deathblade (Radiant)",
        "TFT5_Item_DragonsClawRadiant" to "Dragon's Claw (Radiant)",
        "TFT5_Item_TitansResolveRadiant" to "Titan's Resolve (Radiant)",
        "TFT5_Item_ZzRotPortalRadiant" to "Zz'Rot Portal (Radiant)",
        "TFT5_Item_GuinsoosRagebladeRadiant" to "Guinsoo's Rageblade (Radiant)",
        "TFT5_Item_ArchangelsStaffRadiant" to "Archangel's Staff (Radiant)",
        "TFT5_Item_JeweledGauntletRadiant" to "Jeweled Gauntlet (Radiant)",
        "TFT5_Item_LastWhisperRadiant" to "Last Whisper (Radiant)",
        "TFT5_Item_InfinityEdgeRadiant" to "Infinity Edge (Radiant)",
        "TFT5_Item_RapidFirecannonRadiant" to "Rapid Firecannon (Radiant)",
        "TFT5_Item_SteraksGageRadiant" to "Sterak's Gage (Radiant)",
        "TFT5_Item_TrapClawRadiant" to "Trap Claw (Radiant)",
        "TFT5_Item_LeviathanRadiant" to "Leviathan (Radiant)",
        "TFT5_Item_FrozenHeartRadiant" to "Frozen Heart (Radiant)",

        // Ornn Items (TFT4)
        "TFT4_Item_OrnnAnimaVisage" to "Anima Visage",
        "TFT4_Item_OrnnDeathsDefiance" to "Death's Defiance",
        "TFT4_Item_OrnnMuramana" to "Muramana",
        "TFT4_Item_OrnnInfinityForce" to "Infinity Force",
        "TFT4_Item_OrnnTheCollector" to "The Collector",
        "TFT4_Item_OrnnZhonyasParadox" to "Zhonya's Paradox",
        "TFT4_Item_OrnnRanduinsSanctum" to "Randuin's Sanctum",
        "TFT4_Item_OrnnObsidianCleaver" to "Obsidian Cleaver",
        "TFT9_Item_OrnnTrickstersGlass" to "Trickster's Glass",
        "TFT9_Item_OrnnHorizonFocus" to "Horizon Focus",
        "TFT9_Item_OrnnDeathfireGrasp" to "Deathfire Grasp",
        "TFT9_Item_OrnnHullbreaker" to "Hullbreaker",

        // Artifact Items
        "TFT_Item_Artifact_SpectralCutlass" to "Spectral Cutlass",
        "TFT_Item_Artifact_BlightingJewel" to "Blighting Jewel",
        "TFT_Item_Artifact_SilvermereDawn" to "Silvermere Dawn",
        "TFT_Item_Artifact_UnendingDespair" to "Unending Despair",
        "TFT_Item_Artifact_SuspiciousTrenchCoat" to "Suspicious Trench Coat",
        "TFT_Item_Artifact_Fishbones" to "Fishbones",
        "TFT_Item_Artifact_SeekersArmguard" to "Seeker's Armguard",
        "TFT_Item_Artifact_LudensTempest" to "Luden's Tempest",
        "TFT_Item_Artifact_LichBane" to "Lich Bane",
        "TFT_Item_Artifact_Mittens" to "Mittens",
        "TFT_Item_Artifact_LightshieldCrest" to "Lightshield Crest",
        "TFT_Item_Artifact_HorizonFocus" to "Horizon Focus",
        "TFT_Item_Artifact_ProwlersClaw" to "Prowler's Claw",
        "TFT_Item_Artifact_RapidFirecannon" to "Rapid Firecannon",
        "TFT_Item_Artifact_InnervatingLocket" to "Innervating Locket",
        "TFT_Item_Artifact_WitsEnd" to "Wit's End (Artifact)",
        "TFT_Item_Artifact_TalismanOfAscension" to "Talisman of Ascension",
        "TFT7_Item_ShimmerscaleHeartOfGold" to "Heart of Gold",
        "TFT7_Item_ShimmerscaleGamblersBlade" to "Gambler's Blade",
        "TFT7_Item_ShimmerscaleMogulsMail" to "Mogul's Mail",

        // TFT14 Emblem Items
        "TFT14_Item_ArmorcladEmblemItem" to "Armorclad Emblem",
        "TFT14_Item_DivinicorpEmblemItem" to "Divinicorp Emblem",
        "TFT14_Item_DarkWebEmblemItem" to "Dark Web Emblem",
        "TFT14_Item_ControllerEmblemItem" to "Controller Emblem",
        "TFT14_Item_GuardianEmblemItem" to "Guardian Emblem",
        "TFT14_Item_MarksmanEmblemItem" to "Marksman Emblem",
        "TFT14_Item_MobEmblemItem" to "Mob Emblem",
        "TFT14_Item_SwiftEmblemItem" to "Swift Emblem",
        "TFT14_Item_BallistekEmblemItem" to "Ballistek Emblem",
        "TFT14_Item_ThirstyEmblemItem" to "Thirsty Emblem",
        "TFT14_Item_TechieEmblemItem" to "Techie Emblem",
        "TFT14_Item_CutterEmblemItem" to "Cutter Emblem",
        "TFT14_Item_EdgeRunnerEmblemItem" to "Edge Runner Emblem",
        "TFT14_Item_BruiserEmblemItem" to "Bruiser Emblem",
        "TFT14_Item_StreetDemonEmblemItem" to "Street Demon Emblem",
        "TFT14_Item_ImmortalEmblemItem" to "Immortal Emblem",
        "TFT14_Item_StrongEmblemItem" to "Strong Emblem",

        // Special TFT14 Items
        "TFT14_Item_Nitro_ChromeCounter" to "Nitro Chrome Counter"
    )

    fun getReadableItemName(itemString: String): String {
        return tftItemMap[itemString] ?: itemString.replace("TFT_Item_", "").replace("_", " ")
    }

    // Exclude the basic items that build into the completed items
    private val tftItemsToExclude = setOf(
        "TFT_Item_ChainVest",
        "TFT_Item_TearOfTheGoddess",
        "TFT_Item_RecurveBow",
        "TFT_Item_BFSword",
        "TFT_Item_NegatronCloak",
        "TFT_Item_GiantsBelt",
        "TFT_Item_NeedlesslyLargeRod",
        "TFT_Item_SparringGloves",
        "TFT_Item_EmptyBag"
    )

    fun isExcludedItem(itemString: String): Boolean {
        return tftItemsToExclude.contains(itemString)
    }
}